### PR TITLE
Edit environment.yml + Add unit-tests for particle_metadata.ipynb

### PR DESCRIPTION
**Pull request by ninamiolane**
This PR:
- cleans `environment.yml` by removing unnecessary github import of simSPI
- adds `test_notebooks.py` file to test jupyter notebooks
- tests `particle_metadata.ipynb`

Note that `download_and_upload_with_osf.ipynb` is not tested as the jupyter notebook is currently running for too long.

### CODE REVIEW

**Comment by ninamiolane** [comment]
There is a problem in this PR, as the unit-tests of ioSPI are taking over an hour, due to the installation of conda dependencies. (see screenshot below)

We should investigate the source of the problem, and add a fix so that the unit-tests do not take as long, because unit-tests that take over an hour will prevent many contributors from adding code to the library, as it will be very frustrating.

The conda dependencies are in the environment.yml file at the root of the repository. The long unit-tests have first been observed in PR #75 , but not in other recent PRs, thus it should come from additions made in this PR: the install of jupyter or the install of osfclient maybe?


Screen Shot 2022-05-09 at 2 16 07 PM

**Comment by ninamiolane** [comment]
Installing jupyter (via pip) in geomstats' workflows does not take as long:
https://github.com/geomstats/geomstats/blob/a7bb7e80802727312221e3d18f86bbb2c40a4825/.github/workflows/test.yml#L47

jupyter is in doc requirements:
https://github.com/geomstats/geomstats/blob/a7bb7e80802727312221e3d18f86bbb2c40a4825/setup.cfg#L56

**Comment by artajmir3** [comment]
FYI, I've encountered the same issue in PR #83 exactly after the commit that added Jupiter notebook to `enviroment.yml`, and there is no` osfclient` in that PR. Hence, I think the issue is probably with the installation of Jupiter.

**Comment by ninamiolane** [comment]
@artajmir3 thanks for the insight! Yes, we are not sure why this is taking so long. Let us know if you find out how to solve this jupyter issue? We need to solve it before we can merge this PR and your PR :)

**Comment by bongjinkoo** [comment]
The same path problem occurred when installing jupyter with pip. Also, subprocess.check_call() didn't work. So I changed it to subprocess.run() and it works now. I think the DeppSource error can be ignored.

**Review by ninamiolane — COMMENTED** [review]
Thank you @bongjinkoo !!

**Pull request merged**
