### PR TITLE
Add programmatic way to download and upload data to OSF - link to an existing project with 80s data

### PR DESCRIPTION
**Pull request by ninamiolane**
This PR:
- adds a `Project` class in `datasets.py` that allows to list, download, and upload data from an OSF project.
- demonstrates its use through a notebook that download simulated ribosome data from an existing OSF project.

### CODE REVIEW

**Comment by geoffwoollard** [comment]
I looked at the notebooks and see how the `download` method of the `Project` class works. Are you still working on the `upload` method?

**Comment by ninamiolane** [comment]
Yes! The upload method does not give any error but does not seem to really upload anything...

Did the download method work for you? (to download from the same project as the one in my notebook?)

**Comment by geoffwoollard** [comment]
What about the missing lines that are not being tested?

```
ioSPI/datasets.py               73     21    71%   31-41, 45-46, 63-65, 86-88, 181
```
https://github.com/compSPI/ioSPI/runs/6282964241?check_suite_focus=true#step:6:24

**Review by ninamiolane — COMMENTED** [review]
Thanks @bongjinkoo ! 

- I have checked the boxes that are done in the checklist of task #73 .
- The box with the unit-tests remains, as mentioned by @geoffwoollard : any chance you could add them?

Since I know you are traveling today, and we need this for the hackathon on Friday, I will merge this PR first. Could you add the unit-tests in a follow-up PR?

Thanks.

**Pull request merged**
